local_costmap:
  global_frame: /odom
  robot_base_frame: /base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 12.0
  height: 10.0
  resolution: 0.025

  plugins:
  - {name: obstacles_layer,        type: "costmap_2d::ObstacleLayer" }
  - {name: inflation_layer,        type: "costmap_2d::InflationLayer" }
  
  # robot radius set to min to pass near obstacles
  # #inflation_radius: 0.060   
  # inflation_radius: 0.001  
  # # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0  #Padding is extra clearance around the footprint, which is usually used to provide some extra distance between the robot and obstacles as it is navigating.

  inflation_layer:
    enabled: true
    cost_scaling_factor: 0.0 # the lower, the more cost
    inflation_radius: 0.1   # big values make it harder to pass through narrow spaces
