controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 2.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.0
recovery_behavior_enabled: true
recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'

  # - name: 'clear_costmap_recovery'
  #   type: 'clear_costmap_recovery/ClearCostmapRecovery '

aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_2d_layer"]



# recovery_behaviors: [{
#     name: conservative_reset, 
#     type: clear_costmap_recovery/ClearCostmapRecovery
#   }, {
#     name: rotate_recovery1,
#     type: rotate_recovery/RotateRecovery
#   }, {
#     name: aggressive_reset,
#     type: clear_costmap_recovery/ClearCostmapRecovery
#   }, {
#     name: rotate_recovery2,
#     type: rotate_recovery/RotateRecovery
#   }]
  
# planner_frequency:          0     # Global plan updates on new goal or path blocked only
# controller_frequency:       20
# planner_patience:           5.0
# controller_patience:        3.0
# conservative_reset_dist:    2.0
# recovery_behavior_enabled:  true
# clearing_rotation_allowed:  true
# shutdown_costmaps:          false
# oscillation_timeout:        0.0
# oscillation_distance:       0.5