base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map
     
  # Trajectory
   
  teb_autosize: True
  dt_ref: 0.4      # increase this robot not follow global plan accurately
  dt_hysteresis: 0.2
  global_plan_overwrite_orientation: True   # True makes to follow the original global plan
  max_global_plan_lookahead_dist: 8.0         
  feasibility_check_no_poses: 2.0
  global_plan_viapoint_sep: 1.5
  trajectory.global_plan_prune_distance: 1.0
  # publish_feedback: True
     
  # Robot
          
  max_vel_x: 1.8
  max_vel_x_backwards: 0.5
  max_vel_y: 0.4
  max_vel_theta: 0.4
  acc_lim_x: 1.2
  acc_lim_y: 0.2
  acc_lim_theta: 0.4
  min_turning_radius: 8.0   #depending on vehicle wheelbase
  wheelbase: 2.5
  cmd_angle_instead_rotvel: True # set true in ackermann mode
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    #type: "point"
    #type: "circular"
    #radius: 0.25 
    #type: "line"
    #line_start: [-0.6, 0.0] 
    #line_end: [0.6, 0.0] 
    #type: "two_circles"
    #front_offset: 0.2 
    #front_radius: 0.2 
    #rear_offset: 0.2 
    #rear_radius: 0.2 
    type: "polygon"
    vertices: [[-2,-0.61],[1.8,-0.61],[1.8,0.61],[-2,0.61]]
 
  # GoalTolerance
     
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.25
  free_goal_vel: False
     
  # Obstacles
     
  min_obstacle_dist: 0.8  #maintain distance between obstracle reduce this when passing betwn walls
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 0.5
  obstacle_poses_affected: 10
  include_dynamic_obstacles: true
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"   #this plugin creates polygon around obstracle
  # costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  #costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  #costmap_converter_plugin: "" # deactivate plugin
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  # costmap_converter/CostmapToLinesDBSRANSAC:
  #    cluster_max_distance: 0.4
 
  # Optimization
     
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2   #increase these planner effectively applies velocities
  weight_max_vel_y: 1
  weight_max_vel_theta: 2
  weight_acc_lim_x: 2
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 100
  weight_kinematics_turning_radius: 50
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_viapoint: 5
  weight_dynamic_obstacle: 10 # not in use yet
  selection_alternative_time_cost: False 
 
  # Homotopy Class Planner
 
  enable_homotopy_class_planning: False   #if u make it true this will generate a new plan opp. to teb plan & consumes high processor
  enable_multithreading: True
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_prefer_initial_plan: 0.95
  selection_viapoint_cost_scale: 1.0
  simple_exploration: False
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
